sudo: false
addons:
  sauce_connect: true
branches:
  only:
    - master
    - /^v.*$/ # Tagged builds (Travis branch name = tag name)

jobs:
  include:
    - stage: Test and Deploy
      language: node_js
      node_js: "14" # Must build in Node 8+ (for webpack and babel-loader)
      script:
        - npm run build # test-src, build, test-build-node

        - nvm install 12
        - nvm use 12
        - npm run test-build-node
        
        - nvm install 10
        - nvm use 10
        - npm run test-build-node
        
        - nvm install 8
        - nvm use 8
        - npm run test-build-node

        - nvm install 6
        - nvm use 6
        - npm run test-build-node

        - nvm use 8
        - npm run test-build-browsers # Browser tests only once
        - npm run coveralls
      deploy: # Can't use npm provider because you need to publish the build folder
        provider: script
        skip_cleanup: true # Preserve the build so it can be published
        script:
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >>
          $HOME/.npmrc && npm publish build
        on:
          tags: true # Only deploy to NPM on tagged commits (new versions)
