sudo: false
addons:
  sauce_connect: true
branches:
  only:
    - master

jobs:
  include:
    - stage: Test # Don't test widely unless target v6 works (smoke test)
      language: node_js
      node_js: "6"
      script:
        - npm run build # test-src, build, test-build-node
        - npm run test-build-browsers # Browser tests only once
        - npm run coveralls
    - stage: Test
      language: node_js
      node_js: "8"
      script: npm run build # test-src, build, test-build-node
    - stage: Test
      language: node_js
      node_js: "10"
      script: npm run build # test-src, build, test-build-node
