# name: build-test-deploy
# run-name: ${{ github.actor }} is learning GitHub Actions 1
# on: [push]
# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '14'
#       - run: npm install -g bats
#       - run: bats -v
      
name: build-test-deploy
run-name: Build, Test, Deploy 1
on:
  - push
  - workflow_dispatch # Permit manual
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm ci
      - run: npm run build