name: build
run-name: Build and Test
on:
  - push
  - workflow_dispatch # Permit manual initiation
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm ci
      - run: npm run build
      #- run: npm run test-build-browsers
      - run: npm run coveralls