name: deploy
run-name: Deploy to NPM
on:
  - push
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm ci
      - run: npm run build
